version: '2'

services:
  tests:
    build:
      context: .
      dockerfile: ./compose/tests/Dockerfile
    volumes:
      - ./htmlcov:/home/circleci/htmlcov
    command: bash .devops/test_and_coverage.sh ${CIRCLE_LOCAL_BUILD}