version: 2

jobs:
    build:
        environment:
            TZ: "/usr/share/zoneinfo/America/Detroit"
        working_directory: ~/app
        machine: true
        steps:

            ##
            # SETUP
            ##
            - run:
                name: Flag local/PR builds
                command: |
                  if [[ "$CIRCLE_BUILD_NUM" == '' ]]; then
                    touch ~/.localCircleBuild
                  fi
                  if [[ "$CIRCLE_PR_USERNAME" != '' ]]; then
                    touch ~/.prCircleBuild
                  fi
            - add_ssh_keys
            - checkout
            - run:
                name: Install jq
                command: |
                  sudo curl -sSL -o /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
                  sudo chmod +x /usr/local/bin/jq
            - run:
                name: Calculate codebase version
                command: |
                  bash .devops/calculate-app-version.sh
                  bash .devops/semverTo440.sh
                  sed -i -e "s/__version__ = .*/__version__ = '$(cat ~/.version440)'/" auklet/__about__.py
                  VERSION_SIMPLE=$(cat ~/.version | xargs | cut -f1 -d"+")
                  sed -i -e "s/__semver__ = .*/__semver__ = '$VERSION_SIMPLE'/" auklet/__about__.py
            - run:
                name: Upgrade Docker Compose
                command: |
                  set -x
                  curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ./docker-compose
                  chmod +x ./docker-compose
                  sudo mv ./docker-compose /usr/local/bin

            ##
            # RESTORE CACHES
            ##
            - restore_cache:
                key: v1-whitesource-cache-{{ checksum "requirements.txt" }}
            - restore_cache:
                key: v1-pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}
            - run:
                name: Ensure caches exist
                command: |
                  mkdir -p ~/.cache/pip ~/.whitesource-pip

            ##
            # DOCKER
            ##
            - run:
                name: Show Docker Versions
                command: |
                  set -x
                  docker --version
                  docker-compose --version
            - run:
                name: Setup Environment
                command: |
                  env > ~/app/.env
            - run:
                name: Build Docker Application
                command: |
                  set -x
                  docker-compose build

            ##
            # TESTS
            ##
            - run:
                name: Run Tests
                command: |
                  docker-compose run tests
            - store_artifacts:
                  path: ~/app/htmlcov
            - run:
                name: Run benchmark tests
                command: |
                  export PYTHONUNBUFFERED=0
                  mkdir .auklet
                  sudo python3 setup.py install
                  python3 src/benchmark/run_tests.py
            - run:
                name: Run Whitesource
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild && ! -f ~/.prCircleBuild ]]; then
                    bash .devops/whitesource.sh
                  fi

            ##
            # SAVE CACHES
            ##
            - save_cache:
                key: v1-whitesource-cache-{{ checksum "requirements.txt" }}
                paths:
                    - /home/circleci/.whitesource-pip
            - save_cache:
                key: v1-pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}
                paths:
                    - /home/circleci/.cache/pip

            ##
            # DEPLOYMENT
            ##
            - run:
                name: Deploy Beta (master)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      bash .devops/deploy.sh beta
                    fi
                  fi
            - run:
                name: Deploy RC (rc)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "rc" ]; then
                      bash .devops/deploy.sh rc
                      bash .devops/post-release.sh
                      # Need to checkout rc again so we can run more scripts.
                      git checkout rc
                      bash .devops/updateProdReleasePr.sh
                    fi
                  fi
            - run:
                name: Deploy Production (release)
                command: |
                  set -ou pipefail
                  if [[ ! -f ~/.localCircleBuild ]]; then
                    if [ "${CIRCLE_BRANCH}" == "release" ]; then
                      bash .devops/deploy.sh release
                      bash .devops/post-release.sh
                    fi
                  fi
